baloise/gitopscli

README.md, gitopscli/__main__.py, gitopscli/git_util.py
As GitPython doesn't directly support Basic Auth, it could be implemented by adding the repository URL using the following pattern:
```
--repo https://$GIT_USER:$GIT_PASSWORD@gitserver.tld/repo.git
```
The downside is that the URL appears in Exceptions which would lead to exposing the password.
Alternatively, a credential helper could be provided with the corresponding password as file. This approach is implemented with this PR. The credentials are passed with `--username` and `--password`
=> Add username/password parameters to support Basic Auth

gitopscli/__main__.py
This enables the usage of the `deploy` command without the need of merging/creating a PR
=> Set default branch to master

gitopscli/__main__.py, gitopscli/github_git_util.py, requirements.txt
We probably should also support token auth:
```
Hi @christiansiegel,
You recently used a password to access an endpoint through the GitHub API using PyGithub/Python. We will deprecate basic authentication using password to this endpoint soon:
https://api.github.com/repositories/235198591
We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.
Thanks,
The GitHub Team
```
=> Add Github support

doc/commands/deploy.md, gitopscli/cliparser.py, gitopscli/commands/deploy.py, gitopscli/yaml/yaml_util.py, tests/test_yaml_util.py
- display updated values as YAML instead of JSON in PR
- display only *updated* values in PR
- shorten deploy PR message
- add `--single-commit` flag to deploy cmd
=> Add `--single-commit` flag to deploy cmd

.gitignore, .gitpod.yml, Dockerfile, Makefile, README.md, docs/getting-started.md, docs/index.md, docs/setup.md, mkdocs.yml, requirements.txt, setup.py
- add short setup and getting started guide
- move requirements to setup.py to allow full installation from source with only `pip3 install .`
Resolves #58
=> Add short getting started doc

docs/commands/create-preview.md, docs/commands/delete-preview.md
=> improve preview doc

CHANGELOG.md, docs/commands/create-preview.md, docs/commands/delete-preview.md, docs/commands/deploy.md, gitopscli/cliparser.py, gitopscli/commands/create_preview.py, gitopscli/commands/delete_preview.py, gitopscli/commands/deploy.py, gitopscli/git/abstract_git_util.py, gitopscli/git/bitbucket_git_util.py, gitopscli/git/github_git_util.py
Background:
The `--branch` arg was used to create the config PR branch _AND_ to
locate the PR branch in case of `create-preview` and `delete-preview`.
This is confusing for the user and can potentially lead to branch
collisions in the config repo.
Solution:
- Randomly create branch names for the config repo (if `--create_pr` is
given) or directly push to the master branch.
- In case of `create-preview`, get the PR branch name through the API
via `--pr_id`
- In case of `delete-preview` we still need to know the branch name. For
this reason, this is the only command which still has the arg `--branch`.
=> Remove --branch arg

gitopscli/commands/sync_apps.py
When syncing multiple apps at the same time, the application objects
in the root repo contained YAML anchors:
```yaml
applications:
menu-service: &id001 {}
pizzeria-application: *id001
stock-service: *id001
```
Fixes #86
=> fix(sync-apps): prevent YAML anchors in application objects

docs/commands/deploy.md, gitopscli/yaml/yaml_util.py, tests/yaml/test_yaml_util.py
Support YAML paths containing array indexes, e.g. `a.b.[1].c` for 
```yaml
a:
b:
- foo
- c: bar
`
=> feat(deploy): add support for updating values in YAML arrays

.releaserc.yml, .travis.yml
1. replace [semantic-release-docker](https://github.com/felixfbecker/semantic-release-docker)  plugin
2. push additional `<major>` and `<major>.<minor>` tags to Docker Hub
The [semantic-release-docker](https://github.com/felixfbecker/semantic-release-docker) plugin is not very actively maintained and lacks a feature we need. If it supports `<major>` and `<major>.<minor>` tags in the future, we can switch back.
Fixes #88
=> Replace semantic-release-docker plugin with bash commands + push additional tags

gitopscli/commands/delete_preview.py
- only create new branch in config repo if `--create-pr`
- improve error message for missing `.gitops.config.yaml`
=> fix(delete-preview): fix bug when pushing directly to master + improve error log

docs/commands/delete-pr-preview.md, docs/commands/delete-preview.md, gitopscli/cliparser.py, gitopscli/commands/delete_pr_preview.py, gitopscli/commands/delete_preview.py, tests/commands/test_delete_preview.py, tests/test_cliparser.py
If a preview doesn't exist yet, `delete-(pr-)-preview` should run successfully since nothing needs to be done. Only if the new flag `--expect-preview-exists` is set, it should fail.
Fixes #102
=> feat(delete-preview,delete-pr-preview): add  flag --expect-preview-exists

gitopscli/commands/create_preview.py
=> fix(create-preview,create-pr-preview): Create only one commit when creating a new preview folder

gitopscli/commands/add_pr_comment.py, gitopscli/commands/create_pr_preview.py, gitopscli/commands/create_preview.py, gitopscli/commands/delete_pr_preview.py, gitopscli/commands/delete_preview.py, gitopscli/commands/deploy.py, gitopscli/commands/sync_apps.py, gitopscli/git/abstract_git_util.py, gitopscli/git/bitbucket_git_util.py, gitopscli/git/create_git.py, gitopscli/git/github_git_util.py, tests/commands/test_delete_preview.py, tests/commands/test_deploy.py, tests/git/test_abstract_git_util.py, tests/git/test_create_git.py
Users of GitUtil should not need to think about creation and deletion of a temporary workdir to checkout the repo.
=> chore(refactor): move tmp dir creation/deletion to AbstractGitUtil

gitopscli/commands/add_pr_comment.py, gitopscli/commands/create_pr_preview.py, gitopscli/commands/create_preview.py, gitopscli/commands/delete_preview.py, gitopscli/commands/deploy.py, gitopscli/git/bitbucket_git_repo_api_adapter.py, gitopscli/git/git_repo.py, gitopscli/git/git_repo_api.py, gitopscli/git/git_repo_api_factory.py, gitopscli/git/git_repo_api_logging_proxy.py, gitopscli/git/github_git_repo_api_adapter.py, tests/commands/test_add_pr_comment.py, tests/commands/test_delete_pr_preview.py, tests/commands/test_delete_preview.py, tests/commands/test_deploy.py, tests/git/test_git_repo.py, tests/git/test_git_repo_api_logging_proxy.py, tests/git/test_repo_api_factory.py
- add `GitRepoApiLoggingProxy`
- move API related logging into `GitRepoApiLoggingProxy`
- move 'classic' git related logging into `GitRepo`
=> Move git related logging into single place

docs/commands/create-preview.md, gitopscli/commands/create_preview.py, gitopscli/gitops_config.py, tests/commands/test_create_preview.py
Create a tmp file with generated preview infos like the route containing the hashed preview id. This can be used for accessing the preview in following steps of the CI pipeline (e.g. cypress tests).
=> feat(create-preview): return preview info as tmp file

README.md, gitopscli/cliparser.py, gitopscli/git_api/git_provider.py, gitopscli/git_api/git_repo_api_factory.py, gitopscli/git_api/gitlab_git_repo_api_adapter.py, setup.py
👋 
Support for gitlab.com or self-hosted instances:
```sh
docker run --rm -it gitopscli:latest deploy --file values.yaml --values "{ app.image.tag: 2.5.0 }" --username GitOps --password 1GdNwR2QDit6xjwGxkjC --organisation "not needed" --repository-name 301 --git-provider-url "https://gitlab.yourorg.com" --create-pr --auto-merge
```
```sh
docker run --rm -it gitopscli:latest deploy --file values.yaml --values "{ app.image.tag: 2.5.0 }" --username GitOps --password JzKPDUmNvbvmohNypmb4 --organisation "not needed" --repository-name 24029565 --git-provider gitlab --create-pr --auto-merge
```
To authenticate you have to create a  [personal access token](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#creating-a-personal-access-token). Username and password then correspond …
=> feat(gitlab): added gitlab repository support

docs/commands/create-pr-preview.md
In #37 the args create-pr & auto-merge for create-pr-preview were removed but the doc isn't updated.
=> Remove args from doc which went obsolete in #37

docs/commands/add-pr-comment.md, docs/commands/create-pr-preview.md, docs/commands/create-preview.md, docs/commands/delete-pr-preview.md, docs/commands/delete-preview.md, docs/commands/deploy.md, docs/commands/sync-apps.md, gitopscli/cliparser.py, tests/test_cliparser.py
- `GITOPSCLI_USERNAME` instead of `--username`
- `GITOPSCLI_PASSWORD` instead of `--password`
Resolves #146
=> feat(cli): allow passing credentials via environment variables

gitopscli/io_api/yaml_util.py, tests/io_api/test_yaml_util.py
Preserve existing quotes in YAML files. The philosophy of the gitopscli is to only change the absolute minimum when applying YAML updates.
Fixes #152
=> fix: preserve existing yaml quotes during update

.pre-commit-config.yaml, Makefile, README.md, gitopscli/git_api/git_repo.py, requirements-dev.txt, tests/git_api/test_git_repo.py
Run all checks before every commit for immediate developer feedback.
Necessary fix: Running the tests in the pre-commit hook somehow messes
with the git user/email config used for creating commits during the
tests. Additionally specifying the author of the commits works.
=> build: add pre-commit hooks

docs/includes/preview-configuration.md, gitopscli/gitops_config.py, tests/commands/test_create_preview.py, tests/commands/test_delete_preview.py, tests/test_gitops_config_v0.py, tests/test_gitops_config_v2.py
1. doc(GitOpsConfig): Fix config example
- Fixes #162 (until we officially release and document apiVersion v2)
2. feat(GitOpsConfig): introduce apiVersion v2_beta
- Version 2 will use different string interpolation (`${VAR}` instead of `{VAR}`). This fixes #162.
- Version 1 is kept with simple backwards compatability by replacing old variable placeholders with new ones.
- Version 2 is still beta and not mentioned in the docs yet. This way we can add some more breaking improvements.
=> New variable syntax

gitopscli/gitops_config.py, tests/commands/test_create_preview.py, tests/commands/test_delete_preview.py, tests/test_gitops_config_v2.py
Default to 53 (max Helm release name) instead of 63 (max k8s namespace).
Fixes #163
(Also updated converter: https://christiansiegel.github.io/gitopscli-config-converter/)
(Discussed short preview id hash will be another patch)
=> feat(GitOpsConfig): add namespaceMaxLength

gitopscli/git_api/git_repo.py, tests/git_api/test_git_repo.py
To support special characters like \ or # in credentials, single quotes are added
=> Add single quotes around username/password to credentials helper

requirements-dev.txt
Our code formatter `black` uses sub-dependency `click`. The minor release of `click` from 8.0.4 to 8.1.0 breaks `black`. See also https://github.com/psf/black/issues/2964
Quick workaround: Pin `click` to an older version.
Longterm fix: Upgrade `black` to the most recent version. However, this changes the formatting in a few places. That's why I wanted to wait until the other PRs are merged to prevent merge conflicts.
=> ci: fix black formatter by pinning click dependency version

docs/includes/preview-configuration.md, gitopscli/commands/create_pr_preview.py, gitopscli/commands/create_preview.py, gitopscli/gitops_config.py, tests/commands/test_create_pr_preview.py, tests/commands/test_create_preview.py, tests/commands/test_delete_preview.py
Allows one to define custom message templates in the .gitops.config.yml which are used for the PR comments
If no templates are specified, default messages are used
Example .gitops.config.yml
```apiVersion: v2
applicationName: my-application
messages:
created: "Created preview for ${GIT_HASH}. You can access your application here: https://prefix-${PREVIEW_HOST}/some-cool-path"
updated: "Updated preview to ${GIT_HASH}. You can access your application here: https://prefix-${PREVIEW_HOST}/some-cool-path"
uptodate: "Your application is already up to date with ${GIT_HASH}. You can access your application here: https://prefix-${PREVIEW_HOST}/some-cool-path"
```
=> feat: use customizable message templates for PR comments

docs/includes/preview-configuration.md
Example .gitops.config.yml used invalid template string for git hash
=> fix typo in documentation

docs/commands/deploy.md, docs/includes/preview-configuration.md, gitopscli/commands/deploy.py, gitopscli/io_api/yaml_util.py, setup.py, tests/commands/test_deploy.py, tests/io_api/test_yaml_util.py
Use library `jsonpath-ng` to replace own but limited JSONPath implementation. Especially the filter expressions allow more complex replacements within lists.
Resolves #181.
=> feat: support JSONPath

.dockerignore, .travis.yml, Dockerfile, Makefile, requirements-docs.txt, requirements-test.txt
We're having odd errors in the travis python runner that I cannot reproduce locally.
Solution: Build docs with docker build. With the BuildKit backend it's quite easy to `--output` the site directory.
=> ci: Build docs with docker

requirements-docs.txt
Markdown >= 3.4.1 seems to have introduced some breaking changes (yay, semver :partying_face:) 
https://github.com/mkdocs/mkdocs/issues/2892
=> ci: pin Markdown version to 3.3.7

docs/commands/deploy.md, gitopscli/cliparser.py, gitopscli/commands/deploy.py, gitopscli/git_api/git_repo.py, tests/commands/test_deploy.py, tests/git_api/test_git_repo.py, tests/test_cliparser.py
I altered the deploy command so that hashes of all commits are printed and we can use them for postprocessing in our pipeline. I had to update black and reformat a couple of files because of a [compatibility issue](https://github.com/psf/black/issues/2964). Unfortunately I couldn't think of a good way to test the case when there is no output by the deploy command (when no commits are made). Maybe someone of you has an idea how to cleanly mock the nested call to commit. Also I am not too happy with parsing the short hashes from the command line output but this is the return value I get from the commit method.
=> Print hashes of every commit when deploying

.gitpod.yml, .pylintrc, Dockerfile, Makefile, README.md, docs/commands/add-pr-comment.md, docs/commands/create-pr-preview.md, docs/commands/create-preview.md, docs/commands/delete-pr-preview.md, docs/commands/delete-preview.md, docs/commands/deploy.md, docs/commands/sync-apps.md, docs/commands/version.md, docs/getting-started.md, gitopscli/commands/sync_apps.py, gitopscli/git_api/git_repo.py, gitopscli/git_api/gitlab_git_repo_api_adapter.py, mypy.ini, requirements-test.txt, tests/test_cliparser.py
Update image python to version 3.10.
changes:
- by default argparse prints options: instead of optional arguments:
- typed-ast prerequisite for mypy 0.790 in version 1.4.3 had problem with new python version, upgraded both to latest
- mypy upgrade required exclusion of some paths
- linter recommendation applied - remove f-strings where unused,
=> chore(Upgrade to python 3.10 with compatibility fixes)

Makefile, docs/commands/sync-apps.md, gitopscli/commands/sync_apps.py, tests/commands/test_sync_apps.py
Bootstrap file format in root repository was changed. Currently gitopscli will recognize old and new style bootstrap/values.yam;
=> Support new schema

.github/workflows/release.yml, .releaserc.yml
This is a PR to update the semantic-release-replace-plugin to the [new package](https://www.npmjs.com/package/semantic-release-replace-plugin) from the [deprecated version](https://www.npmjs.com/package/@google/semantic-release-replace-plugin).
=> chore: update deprecated plugin to new package

gitopscli/appconfig_api/app_tenant_config.py
Seems to be the cause of
```
INFO __sync_apps: Found 6 app(s) in apps repository: ....., cop-3299-test, cop-3299-prod, ....
07:49:02  --- Logging error ---
07:49:02  Traceback (most recent call last):
07:49:02    File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
07:49:02      msg = self.format(record)
07:49:02    File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
07:49:02      return fmt.format(record)
07:49:02    File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
07:49:02      record.message = record.getMessage()
07:49:02    File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
07:49:02      msg = msg % self.args
07:49:02  TypeError: %i format: a real number is required, not str
07:49:02  Call …
```
=> fix(log-formatting): correct missing coversion type / wrong conversion flag for info log line

tests/git_api/test_git_repo.py
Fix git integration test by explicitly setting the initial git branch in case the user installation uses a different default branch name.
=> test: set initial git branch

gitopscli/commands/create_preview.py, gitopscli/commands/delete_preview.py, gitopscli/commands/deploy.py, gitopscli/commands/sync_apps.py, gitopscli/git_api/git_repo.py, tests/commands/test_create_preview.py, tests/commands/test_delete_preview.py, tests/commands/test_deploy.py, tests/commands/test_sync_apps.py, tests/git_api/test_git_repo.py
Resolves #229
If another user pushes changes to the remote repo after gitopscli has cloned it, the subsequent push will fail. Alliviate this problem somewhat by pulling and rebasing local changes on top of any remote changes just before pushing.
For the case of creating a new branch (for a PR), the pull is skipped because it would fail due to the missing remote branch.
=> feat: Pull and rebase before push
