baloise/gitopscli

- gitopscli/__main__.py
- gitopscli/git_util.py
- requirements.txt
* Use "deploy" command to create PRs 
* Use atlassian-python-api lib to support bitbucket-server
* Add --create-pr argument
* Add --auto-merge to automatically merge the created PR
Example command: 
```
gitopscli deploy --repo https://bitbucket.baloise.dev/scm/dpl/incubator-non-prod.git \
--file example/values.yaml \
--branch deploy-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 5 | head -n 1) \
--values "{image.tag: v0.3.0}" \
--username $GIT_USERNAME \
--password $GIT_PASSWORD \
--create-pr \
--auto-merge \
--organisation "DPL" \
--repository-name "incubator-non-prod" \
--git-provider-url https://bitbucket.baloise.dev
```
Output:
```
Pull request created: https://bitbucket.baloise.dev/projects/DPL/repos/incubator-non-prod/pull-requests/15
Pull request merged
```
> Add Pull Request support

- gitopscli/__main__.py
- gitopscli/abstract_git_util.py
- gitopscli/bitbucket_git_util.py
- gitopscli/github_git_util.py
> Delete branch after merge

- .dockerignore
- Dockerfile
- Makefile
- gitopscli/yaml_util.py
- requirements-dev.txt
- tests/test_yaml_util.py
> Add unit tests

- README.md
Closes #19  first draft as a base for discussion
> Add some basic readme enhancements

- README.md
- gitopscli/__main__.py
- gitopscli/abstract_git_util.py
- gitopscli/bitbucket_git_util.py
To support "Verify Committer - Reject commits not committed by the user pushing to this repository" the git user and email must be configurable
> Add --git-user and --git-email as parameter

- gitopscli/commands/deploy.py
- gitopscli/yaml/yaml_util.py
- tests/test_yaml_util.py
> Don't crash on deploy if all values up-to-date

- .dockerignore
- Dockerfile
- Makefile
- gitopscli/git/abstract_git_util.py
- setup.py
- fix install by including submodules in `setup.py`
- use alpine base image & optimize multi-stage build -> reduce image size from 278 to 136 MB
> Fix & Optimize Docker Build

- CHANGELOG.md
- doc/commands/delete-preview.md
- gitopscli/__main__.py
- gitopscli/cliparser.py
- gitopscli/commands/create_preview.py
- gitopscli/commands/delete_preview.py
- setup.py
https://bitbucket.baloise.dev/projects/DPL/repos/incubator-non-prod/pull-requests/78/diff
Running it again: 
INFO delete_preview_command: There was no preview with name: example-32a0668e-preview
> Add delete preview cmd

- .travis.yml
- Makefile
> split docker build in stages

- gitopscli/commands/add_pr_comment.py
- gitopscli/git/github_git_util.py
> handle github errors for add-pr-commment

- docs/commands/sync-apps.md
- gitopscli/cliparser.py
> Improve sync-apps doc

- gitopscli/commands/create_preview.py
- gitopscli/commands/delete_preview.py
...plus some minor cleanups and typo fixes
> Fix create-preview commit msg

- gitopscli/commands/delete_pr_preview.py
> fix(delete-pr-preview command): only hash branch name inside delete preview command

- gitopscli/git/abstract_git_util.py
- tests/git/test_abstract_git_util.py
Signed-off-by: Peter Kullmann <peter.kullmann@baloise.ch>
> Fix #108: Show more info in case a push is rejected by git hooks

- .coveragerc
- .gitignore
- Makefile
- requirements-dev.txt
new make targets:
- `make coverage`: creates coverage html + prints coverage to console
- `make checks`: convenience shortcut for format check + lint + test
> Add coverage check

- README.md
> (build) migrate to travis.com

- Dockerfile
- Makefile
- gitopscli/cliparser.py
- gitopscli/commands/add_pr_comment.py
- gitopscli/commands/create_pr_preview.py
- gitopscli/commands/create_preview.py
- gitopscli/commands/delete_pr_preview.py
- gitopscli/commands/delete_preview.py
- gitopscli/commands/deploy.py
- gitopscli/commands/sync_apps.py
- gitopscli/commands/version.py
- gitopscli/git/bitbucket_git_repo_api_adapter.py
- gitopscli/git/git_repo.py
- gitopscli/git/git_repo_api.py
- gitopscli/git/git_repo_api_logging_proxy.py
- gitopscli/git/github_git_repo_api_adapter.py
- gitopscli/io/gitops_config.py
- gitopscli/io/yaml_util.py
- mypy.ini
- requirements-dev.txt
- tests/commands/test_add_pr_comment.py
- tests/commands/test_delete_pr_preview.py
- tests/commands/test_delete_preview.py
- tests/commands/test_deploy.py
- tests/commands/test_sync_apps.py
- tests/git/test_git_repo.py
- tests/git/test_git_repo_api_logging_proxy.py
- tests/io/test_yaml_util.py
- enable static type checks for all modules with `mypy` 
- add runtime type checks during tests with `typeguard`
> Enable static type checks for all modules

- .pylintrc
- gitopscli/commands/add_pr_comment.py
- gitopscli/commands/create_pr_preview.py
- gitopscli/commands/create_preview.py
- gitopscli/commands/delete_pr_preview.py
- gitopscli/commands/delete_preview.py
- gitopscli/commands/deploy.py
- gitopscli/commands/sync_apps.py
- gitopscli/commands/version.py
- gitopscli/git/git_api_config.py
- tests/commands/test_add_pr_comment.py
- tests/commands/test_delete_pr_preview.py
- tests/commands/test_delete_preview.py
- tests/commands/test_deploy.py
- tests/commands/test_sync_apps.py
This allows to use inheritance from GitApiConfig.
> chore(refactor): use dataclass for command args

- gitopscli/commands/create_pr_preview.py
- gitopscli/commands/create_preview.py
- gitopscli/commands/sync_apps.py
- gitopscli/git/git_repo.py
- gitopscli/io/gitops_config.py
- gitopscli/io/yaml_util.py
- tests/commands/mock_mixin.py
- tests/commands/test_add_pr_comment.py
- tests/commands/test_create_pr_preview.py
- tests/commands/test_create_preview.py
- tests/commands/test_delete_pr_preview.py
- tests/commands/test_delete_preview.py
- tests/commands/test_deploy.py
- tests/commands/test_sync_apps.py
- tests/io/test_yaml_util.py
+ some small fixes here and there
Resolves #82
> Increase test coverage

- gitopscli/commands/create_preview.py
- gitopscli/commands/delete_preview.py
- gitopscli/commands/deploy.py
- gitopscli/commands/sync_apps.py
- gitopscli/gitops_config.py
- tests/commands/test_create_preview.py
- tests/commands/test_delete_preview.py
- tests/commands/test_deploy.py
- tests/test_gitops_config.py
+ move common parts to GitOpsConfig
> refactor(create-preview,delete-preview): re-structure command code

- gitopscli/__main__.py
- gitopscli/cliparser.py
- gitopscli/commands/create_preview.py
- gitopscli/commands/deploy.py
- gitopscli/git/git_repo.py
- gitopscli/io/yaml_util.py
- tests/commands/test_create_preview.py
- tests/commands/test_deploy.py
- tests/io/test_yaml_util.py
- tests/test_cliparser.py
This commit finalizes the long series of refactorings.
IMO the code base is now ready for adding new features without ending up in a total mess.
> fix: some minor fixes and logging improvements

- docs/commands/deploy.md
> doc(deploy): fix examples with list keys

- gitopscli/git_api/gitlab_git_repo_api_adapter.py
I noticed that sometimes the Gitlab Server is not "ready yet" to merge a merge request which results in an `gitlab.exceptions.GitlabMRClosedError: 406: Branch cannot be merged` Exception. When retried after a few seconds it works fine.
> fix(gitlab): retry failed merges due to server still processing merge request

- docs/includes/preview-configuration.md
- gitopscli/gitops_config.py
- tests/test_gitops_config_v2.py
> feat(GitOpsCli): add var PREVIEW_ID_HASH_SHORT

- gitopscli/cliparser.py
- gitopscli/commands/add_pr_comment.py
- gitopscli/commands/create_preview.py
- gitopscli/git_api/git_repo_api_logging_proxy.py
- gitopscli/gitops_config.py
- requirements-dev.txt
- tests/commands/common/test_gitops_config_loader.py
- tests/commands/test_create_preview.py
- tests/commands/test_sync_apps.py
- tests/git_api/test_git_repo_api_logging_proxy.py
- tests/git_api/test_repo_api_factory.py
- tests/test_cliparser.py
Resolves #177 (see also temporary fix #176)
> build(deps-dev): bump black formatter from 19.10b0 to 22.3.0

- .pylintrc
- docs/commands/deploy.md
- gitopscli/cliparser.py
- gitopscli/commands/deploy.py
- gitopscli/git_api/bitbucket_git_repo_api_adapter.py
- gitopscli/git_api/git_repo_api.py
- gitopscli/git_api/git_repo_api_logging_proxy.py
- gitopscli/git_api/github_git_repo_api_adapter.py
- gitopscli/git_api/gitlab_git_repo_api_adapter.py
- mypy.ini
- tests/commands/test_deploy.py
- tests/test_cliparser.py
It's my first draft by issue [193](https://github.com/baloise/gitopscli/issues/193)
Please check if I my approach correct. And tell me what to do next? 
As I have already said I can't test on GitHub, but my code create labels on my Gitlab repository correctly.
Command like 
```
python3 gitopscli  deploy --file values.yaml --single-commit --username epanov --password glpat-password --git-provider GITLAB --repository-name yaml --organisation epanov --git-provider-url https://gitlab.my-infra.ru  --auto-merge --create-pr   --values "{replicaCount: 10}" --pr-labels "{'test', 'helm'}" 
```
> added pr labels for gitlab and github, and merge parameters for gitlab

- docs/setup.md
works for me :) - would be lovely if someone else can test this.
> doc: update setup with poetry
